-- 在 Supabase SQL Editor 中执行此文件

-- 1. profiles 表
CREATE TABLE public.profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_select" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_insert" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profiles_update" ON public.profiles FOR UPDATE USING (auth.uid() = user_id);

-- 2. 邀请码表
CREATE TABLE public.invite_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.invite_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "invite_codes_select" ON public.invite_codes FOR SELECT USING (true);
CREATE POLICY "invite_codes_insert" ON public.invite_codes FOR INSERT WITH CHECK (auth.uid() = created_by);
CREATE POLICY "invite_codes_delete" ON public.invite_codes FOR DELETE USING (auth.uid() = created_by);

-- 3. 用户关系表
CREATE TABLE public.user_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  user_b UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_a, user_b)
);

ALTER TABLE public.user_relations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_relations_select" ON public.user_relations FOR SELECT USING (auth.uid() = user_a OR auth.uid() = user_b);
CREATE POLICY "user_relations_insert" ON public.user_relations FOR INSERT WITH CHECK (auth.uid() = user_a OR auth.uid() = user_b);

-- 4. 心情表
CREATE TABLE public.moods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mood_type TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX moods_user_date ON public.moods(user_id, created_at DESC);

ALTER TABLE public.moods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "moods_select" ON public.moods FOR SELECT USING (true);
CREATE POLICY "moods_insert" ON public.moods FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. 攒钱目标表
CREATE TABLE public.savings_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  target_amount NUMERIC(12,2) NOT NULL,
  current_amount NUMERIC(12,2) DEFAULT 0,
  cover_emoji TEXT DEFAULT '🐷',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "savings_goals_select" ON public.savings_goals FOR SELECT USING (true);
CREATE POLICY "savings_goals_insert" ON public.savings_goals FOR INSERT WITH CHECK (auth.uid() = created_by);
CREATE POLICY "savings_goals_update" ON public.savings_goals FOR UPDATE USING (true);

-- 6. 存款记录表
CREATE TABLE public.savings_contributions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id BIGINT NOT NULL REFERENCES public.savings_goals(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC(12,2) NOT NULL,
  note TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.savings_contributions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "savings_contributions_select" ON public.savings_contributions FOR SELECT USING (true);
CREATE POLICY "savings_contributions_insert" ON public.savings_contributions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 7. 浇水记录表
CREATE TABLE public.plant_waterings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  watered_at DATE NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE public.plant_waterings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plant_waterings_select" ON public.plant_waterings FOR SELECT USING (true);
CREATE POLICY "plant_waterings_insert" ON public.plant_waterings FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 8. 动态表
CREATE TABLE public.moments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  image_urls TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.moments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "moments_select" ON public.moments FOR SELECT USING (true);
CREATE POLICY "moments_insert" ON public.moments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 9. 动态点赞表
CREATE TABLE public.moment_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moment_id BIGINT NOT NULL REFERENCES public.moments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(moment_id, user_id)
);

ALTER TABLE public.moment_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "moment_likes_select" ON public.moment_likes FOR SELECT USING (true);
CREATE POLICY "moment_likes_insert" ON public.moment_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "moment_likes_delete" ON public.moment_likes FOR DELETE USING (auth.uid() = user_id);

-- 10. 动态评论表
CREATE TABLE public.moment_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moment_id BIGINT NOT NULL REFERENCES public.moments(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.moment_comments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "moment_comments_select" ON public.moment_comments FOR SELECT USING (true);
CREATE POLICY "moment_comments_insert" ON public.moment_comments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 11. 创建 profiles 触发器（注册时自动创建）
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, nickname)
  VALUES (NEW.id, split_part(NEW.email, '@', 1));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
